module.exports.descriptors = [
    'Forêt',
    'Ancien',
    'Pétrifié',
    'Rugissant',
    'Cascade',
    'Dévalant',
    'Silencieux',
    'Séquoia',
    'Grenouille-taureau',
    'Érable',
    'Brumeux',
    'Élan',
    'Grizzly',
    'Océan',
    'Mer',
    'Ciel',
    'Poussiéreux',
    'Diamant'
]


module.exports.places = [
    'Plaines',
    'Village',
    'Canyon',
    'Étang',
    'Campement de groupe',
    'Camp de chevaux',
    'Ville fantôme',
    'Camp',
    'Campement dispersé',
    'Arrière-pays',
    'Rivière',
    'Ruisseau',
    'Bord de ruisseau',
    'Baie',
    'Source',
    'Rivage',
    'Sables',
    'Camp de mules',
    'Camp de chasse',
    'Falaises',
    'Creux'
]


module.exports.descriptions = [
    'Découvrez la majestueuse beauté d\'un camping où la nature semble se suspendre dans le temps. Le site est un véritable havre de paix qui évoque la grandeur des paysages préhistoriques.',
    'Laissez-vous envoûter par la sérénité d\'un camping idyllique, enveloppé d\'un charme tranquille qui inspire la réflexion et la tranquillité intérieure.',
    'L\'attrait mystérieux d\'un camping isolé est accentué par une atmosphère saisissante, vous invitant à explorer ses secrets cachés et ses merveilles naturelles.',
    'Les paysages spectaculaires d\'un camping en pleine nature sont sublimés par une vue impressionnante, offrant une expérience sensorielle inégalée.',
    'En vous aventurant dans un camping pittoresque, vous serez accueilli par une vue éblouissante qui transforme chaque moment en une aventure visuelle époustouflante.',
    'L\'élégance d\'un camping au bord de l\'eau se révèle à travers un paysage captivant, créant une atmosphère enchâssée dans la beauté naturelle et la splendeur tranquille.',
    'Plongez dans la grandeur d\'un camping en forêt où chaque recoin est illuminé par un décor majestueux qui respire l\'énergie et la majesté d\'une nature intemporelle.',
    'Les paysages d\'un camping en montagne se dévoilent sous une lumière fascinante, offrant une escapade parfaite dans un environnement où chaque détail est empreint de charme.',
    'La beauté naturelle d\'un camping en bord de lac est magnifiée par un décor impressionnant, offrant un contraste saisissant avec la quiétude du paysage environnant.',
    'Explorez un camping magique et laissez-vous émerveiller par une vue splendide qui ajoute une touche de magie à chaque moment passé dans ce cadre enchanteur.',
    'Le charme intemporel d\'un camping en pleine nature est enrichi par une ambiance étonnante, créant une atmosphère qui captive les sens et invite à l\'émerveillement.',
    'Venez découvrir un camping où un décor majestueux transforme le paysage en une scène de beauté pure et de sérénité.',
    'Les panoramas d\'un camping en haute altitude sont sublimés par une vue éblouissante, offrant un spectacle naturel inégalé et une expérience de tranquillité rare.',
    'Laissez-vous envoûter par la magie d\'un camping au cœur des bois, où un paysage grandiose orne chaque vue, faisant de chaque moment un souvenir mémorable.',
    'L\'attrait captivant d\'un camping au bord de la rivière est enrichi par une ambiance exceptionnelle, transformant le paysage en une toile vivante de beauté et de mystère.',
    'Les paysages enchâssés dans un camping en pleine forêt prennent vie grâce à une vue fascinante, vous invitant à découvrir un monde où chaque détail rayonne de splendeur.',
    'À un camping enchanteur, une ambiance magique déploie une magie subtile, transformant chaque visite en une expérience inoubliable et profondément réconfortante.',
    'L\'atmosphère paisible d\'un camping en bord de mer est accentuée par une vue impressionnante, vous plongeant dans un cadre naturel où la beauté règne en maître.',
    'Découvrez le charme raffiné d\'un camping dans les dunes, où un décor élégant sublime le paysage et transforme chaque moment passé dans ce cadre en une aventure inoubliable.',
    'L\'élégance sereine d\'un camping dans un vallon est amplifiée par une vue fascinante, créant un sanctuaire de paix et de beauté où chaque regard est émerveillé.',
    'Un camping spectaculaire ajoute une dimension époustouflante à chaque vue, faisant de ce lieu un paradis naturel pour les amoureux de la nature.'
]